
[theme]
primaryColor = '#FFC306'
backgroundColor = '#EAF5FD'
secondaryBackgroundColor = '#3CA0FF'
textColor = '#233141'
font = "sans serif"

[logger]

# Level of logging: 'error', 'warning', 'info', or 'debug'.
# Default: 'info'
level = "debug"

# String format for logging messages. If logger.datetimeFormat is set, logger messages will default to `%(asctime)s.%(msecs)03d %(message)s`. See [Python's documentation](https://docs.python.org/2.6/library/logging.html#formatter-objects) for available attributes.
# Default: "%(asctime)s %(message)s"
messageFormat = "%(levelname)s - %(asctime)s %(message)s"
